WORD_LENGTH = 5
DEFAULT_MAX_ATTEMPTS = 6
WORDS_FILE = "words.txt"
FILE_ENCODING = "utf-8"

STATUS_CORRECT = "correct"
STATUS_PRESENT = "present"
STATUS_ABSENT = "absent"
LETTER_STATUSES = (STATUS_CORRECT, STATUS_PRESENT, STATUS_ABSENT)

